//
//  AnimationPresenter.swift
//  BagAnimations
//
//  Created by kkolontay on 10/30/17.
//  Copyright (c) 2017 kkolontay.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnimationPresentationLogic
{
  func presentSomething(response: Animation.Something.Response)
}

class AnimationPresenter: AnimationPresentationLogic
{
  weak var viewController: AnimationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Animation.Something.Response)
  {
    let viewModel = Animation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
