//
//  ListAnimationPresenter.swift
//  BagAnimations
//
//  Created by kkolontay on 10/30/17.
//  Copyright (c) 2017 kkolontay.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListAnimationPresentationLogic
{
  func presentSomething(response: ListAnimation.Something.Response)
}

class ListAnimationPresenter: ListAnimationPresentationLogic
{
  weak var viewController: ListAnimationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListAnimation.Something.Response)
  {
    let viewModel = ListAnimation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
